  db:
    image: postgres
    env_file: .env
    networks:
      - jengo_django
    ports:
      - "${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: jengo_django
      POSTGRES_USER: jengo_django
      POSTGRES_PASSWORD: changeme
volumes:
  postgres_data:
  static:
