version: '3'

networks:
  jengo_django:

services:
  django:
    build: .
    env_file: .env
    networks:
      - jengo_django
    # Allows running container in dev mode, which loads using bash instead of manage.py
    # Exceptions during development won't require rebuilding the containers
    stdin_open: true
    tty: true
    depends_on:
      - db
  # Build nginx instead of just running, less sloppy way to generate a self signed cert
  nginx:
    networks:
      - jengo_django
    build: nginx
    env_file: .env
    ports:
      - "${NGINX_HTTP_PORT}"
      - "${NGINX_HTTPS_PORT}"
    links:
      - django
    restart: always
