  db:
    # Ran into an SSL bug using latest tag, rolling back to 5.7 which works
    # TODO: Troubleshoot
    image: mysql:5.7
    env_file: .env
    networks:
      - jengo_django
    ports:
      - "${MYSQL_PORT}"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
volumes:
  mysql_data:
  static:
