  db:
    image: mysql
    networks:
      - jengo_django
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - jengo_django_mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: jengo_django
      MYSQL_USER: jengo_django
      MYSQL_PASSWORD: changeme
    labels:
      - "com.joped.jengo_django.description=jengo Django MySQL"
volumes:
  jengo_django_mysql_data:
